# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('workhistory', models.CharField(blank=True, max_length=300, null=True)),
                ('profileurl', models.CharField(blank=True, max_length=300, null=True)),
                ('headline', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('schoolname', models.CharField(blank=True, max_length=300, null=True)),
                ('companyname', models.CharField(blank=True, max_length=300, null=True)),
                ('imageurl', models.URLField(blank=True, max_length=300, null=True)),
                ('skills', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
